# Site settings
title: thomas neidhart - open source projects
email: thomas.neidhart@gmail.com
description: >
  open source software development, bytecode engineering, algorithm design
url: "https://netomi.github.io"
github_username: netomi
repository: netomi/netomi.github.io
google_analytics: UA-70394167-2

# Build settings
markdown: kramdown

highlighter: rouge

plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

feed:
  path: /blog/atom.xml

# Pagination
paginate: 5
paginate_path: "/blog/page:num/"

collections:
  projects:
    output: true
    permalink: /projects/:path/

exclude:
  - .idea
  - .jekyll-cache